### ISSUE TITLE
Ownership transfer to join monster org

### ISSUE THREAD

**Issue by nicoabie** [acarl005/graphsiql#5]
Hi Andrew, 

I recently became a maintainer of JM and I was wondering if you wanna transfer this so we can take care ourselves. 

Thanks for all the great work man!

**Comment by acarl005** [comment]
Hi @nicoabie glad to hear it. I'm happy to help. There's already a fork of it in the join-monster org which is fully up-to-date. Will that suffice? If not, we can delete that and I can transfer this one (or whatever the best way is).

**Comment by nicoabie** [comment]
Hey!

First I make it work again graphsiql but then I wen't further and was able to do something on top of latest graphiql directly https://github.com/join-monster/join-monster/pull/523 so this is no longer necessary.

Thanks again and sorry for the back and forth!
